const handler = async (m, {conn}) => {
  m.reply(global.cusrsovip);
};
handler.command = /^(cursovip|cursoplataformas|cursocc)$/i;
export default handler;
global.cusrsovip = `
🦖💳 CURSO DINO CARDS🦕🚀

INFO:🚀
Wa.me/+56986469687
Wa.me/+56986469687
Wa.me/+56986469687

⚠ CURSO DEDICADO A LA CREACIÓN DE CUENTAS PREMIUM, VIDEOS TUTORIALES, MÉTODOS Y MÁS💳

[⚠] ESTE CURSO TE SERVIRÁ MUCHO, NO ES UN CURSO FAKE NI INSERVIBLE❗

AQUI TE ENSEÑO DESDE LO MÁS BASICO PARA QUE VAYAS ENTENDIENDO🚀

APRENDERAS:💳

🌩 Hacer compras físicas, cómo: 

-ALIEXPRESS 👀

⚠ APRENDERAS A SACAR CUENTAS COMO: ⚠

 💥DISNEY PLUS
💨CRUNCHYROLL
👁PRIME VIDEO
🤠 TIDAL HI-FI PLUS
👾CANVA PRO
🔥 SPOTIFY PREMIUM
💨 DUOLINGO
⚠HBO MAX ANUALES
❄ PARAMOUNT ANUALES
😼YOUTUBE PREMIUM
🤯STAR PLUS
💦RECARGARTE BITS TWITCH
🌚PORNHUB
🚀PEDIDOS ALIEXPRESS

Y MUCHOS MÁS MÉTODOS❗💨

🚀 CONTAMOS CON HERRAMIENTAS DENTRO DEL CURSO, SE  DAN CLASES POR DISCORD, SE TE AÑADE AL GRUPO VIP SEPARADO POR CANALES❄💳

OJO:👀

TAMBIEN PODRAS SACAR TUS CUENTAS AUTOPAY¿QUE SIGNIFICA AUTOPAY? QUE SE PAGAN SOLAS uwu⚠🚀

PRECIO: 25🇵🇪 / 55 🇧🇴 / 8000 🇦🇷 / 9000 🇨🇱

🏦 MÉTODOS DE PAGO💱
🇵🇪🇨🇱🇧🇴🇦🇷🇨🇴🇲🇽🌍
`;
